name: Production build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          ## - macos-latest
          ## - windows-latest
        node-version:
          - "16.17.1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get Timestamp
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: "YYYY-MM-DD-HH-mm-ss"

      - name: SCM Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Modules
        run: npm install

      - name: Build Node Frontend
        run: npm run build

      - name: Upload Frontend Package
        uses: actions/upload-artifact@v3
        with:
          name: frontend-release-${{ steps.time.outputs.time }}
          path: "trunk/build"
